// Mocks generated by Mockito 5.4.6 from annotations
// in Homesol/test/home_page_enhanced_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i4;
import 'dart:io' as _i3;

import 'package:firebase_analytics/firebase_analytics.dart' as _i2;
import 'package:Homesol/models/user_profile.dart' as _i9;
import 'package:Homesol/services/analytics_service.dart' as _i7;
import 'package:Homesol/services/apis/user/user_service.dart' as _i8;
import 'package:Homesol/services/shift_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseAnalyticsObserver_0 extends _i1.SmartFake
    implements _i2.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientRequest_2 extends _i1.SmartFake
    implements _i3.HttpClientRequest {
  _FakeHttpClientRequest_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_3 extends _i1.SmartFake implements Uri {
  _FakeUri_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpHeaders_4 extends _i1.SmartFake implements _i3.HttpHeaders {
  _FakeHttpHeaders_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientResponse_5 extends _i1.SmartFake
    implements _i3.HttpClientResponse {
  _FakeHttpClientResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncoding_6 extends _i1.SmartFake implements _i4.Encoding {
  _FakeEncoding_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocket_7 extends _i1.SmartFake implements _i3.Socket {
  _FakeSocket_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSubscription_8<T> extends _i1.SmartFake
    implements _i5.StreamSubscription<T> {
  _FakeStreamSubscription_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ShiftService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShiftService extends _i1.Mock implements _i6.ShiftService {
  @override
  _i5.Future<List<dynamic>> getShiftTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getShiftTypes, []),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i5.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> checkIn(
    String? deviceId,
    String? deviceType, {
    String? remark,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkIn,
              [deviceId, deviceType],
              {#remark: remark},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> checkOut(
    String? deviceId,
    String? deviceType, {
    String? remark,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkOut,
              [deviceId, deviceType],
              {#remark: remark},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i7.AnalyticsService {
  @override
  _i2.FirebaseAnalyticsObserver get observer =>
      (super.noSuchMethod(
            Invocation.getter(#observer),
            returnValue: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.getter(#observer),
            ),
            returnValueForMissingStub: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.getter(#observer),
            ),
          )
          as _i2.FirebaseAnalyticsObserver);

  @override
  void initialize(_i2.FirebaseAnalytics? analytics) => super.noSuchMethod(
    Invocation.method(#initialize, [analytics]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> logScreenView(String? screenName, {String? screenClass}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logScreenView,
              [screenName],
              {#screenClass: screenClass},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logPropertyView(String? propertyId, String? propertyName) =>
      (super.noSuchMethod(
            Invocation.method(#logPropertyView, [propertyId, propertyName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logPropertySearch(String? searchTerm, int? resultsCount) =>
      (super.noSuchMethod(
            Invocation.method(#logPropertySearch, [searchTerm, resultsCount]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logEnquirySubmitted(
    String? propertyId,
    String? enquiryType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logEnquirySubmitted, [propertyId, enquiryType]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logDeveloperView(
    String? developerId,
    String? developerName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logDeveloperView, [developerId, developerName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logProjectView(String? projectId, String? projectName) =>
      (super.noSuchMethod(
            Invocation.method(#logProjectView, [projectId, projectName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logNotificationOpened(
    String? notificationId,
    String? notificationType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logNotificationOpened, [
              notificationId,
              notificationType,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logShareProperty(String? propertyId, String? shareMethod) =>
      (super.noSuchMethod(
            Invocation.method(#logShareProperty, [propertyId, shareMethod]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logLocationPermissionRequested() =>
      (super.noSuchMethod(
            Invocation.method(#logLocationPermissionRequested, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logLocationPermissionGranted() =>
      (super.noSuchMethod(
            Invocation.method(#logLocationPermissionGranted, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logLocationPermissionDenied() =>
      (super.noSuchMethod(
            Invocation.method(#logLocationPermissionDenied, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logImagePickerUsed(String? source) =>
      (super.noSuchMethod(
            Invocation.method(#logImagePickerUsed, [source]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logThemeChanged(String? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#logThemeChanged, [themeMode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logAppOpened() =>
      (super.noSuchMethod(
            Invocation.method(#logAppOpened, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logAppBackgrounded() =>
      (super.noSuchMethod(
            Invocation.method(#logAppBackgrounded, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logCustomEvent(
    String? eventName,
    Map<String, Object>? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logCustomEvent, [eventName, parameters]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i8.UserService {
  @override
  _i5.Future<_i9.UserProfile?> syncUserProfile({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserProfile, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<_i9.UserProfile?>.value(),
            returnValueForMissingStub: _i5.Future<_i9.UserProfile?>.value(),
          )
          as _i5.Future<_i9.UserProfile?>);

  @override
  _i5.Future<_i9.UserProfile?> fetchUserProfile({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i5.Future<_i9.UserProfile?>.value(),
            returnValueForMissingStub: _i5.Future<_i9.UserProfile?>.value(),
          )
          as _i5.Future<_i9.UserProfile?>);

  @override
  _i5.Future<void> registerDeviceToken({
    required String? brokerId,
    required String? token,
    String? platform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerDeviceToken, [], {
              #brokerId: brokerId,
              #token: token,
              #platform: platform,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.HttpClient {
  @override
  Duration get idleTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#idleTimeout),
            returnValue: _FakeDuration_1(this, Invocation.getter(#idleTimeout)),
            returnValueForMissingStub: _FakeDuration_1(
              this,
              Invocation.getter(#idleTimeout),
            ),
          )
          as Duration);

  @override
  bool get autoUncompress =>
      (super.noSuchMethod(
            Invocation.getter(#autoUncompress),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set idleTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#idleTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set connectionTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#connectionTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxConnectionsPerHost(int? value) => super.noSuchMethod(
    Invocation.setter(#maxConnectionsPerHost, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoUncompress(bool? value) => super.noSuchMethod(
    Invocation.setter(#autoUncompress, value),
    returnValueForMissingStub: null,
  );

  @override
  set userAgent(String? value) => super.noSuchMethod(
    Invocation.setter(#userAgent, value),
    returnValueForMissingStub: null,
  );

  @override
  set authenticate(_i5.Future<bool> Function(Uri, String, String?)? f) =>
      super.noSuchMethod(
        Invocation.setter(#authenticate, f),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
    _i5.Future<_i3.ConnectionTask<_i3.Socket>> Function(Uri, String?, int?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#connectionFactory, f),
    returnValueForMissingStub: null,
  );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
    Invocation.setter(#findProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set authenticateProxy(
    _i5.Future<bool> Function(String, int, String, String?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#authenticateProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set badCertificateCallback(
    bool Function(_i3.X509Certificate, String, int)? callback,
  ) => super.noSuchMethod(
    Invocation.setter(#badCertificateCallback, callback),
    returnValueForMissingStub: null,
  );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.setter(#keyLog, callback),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#open, [method, host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> openUrl(String? method, Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#openUrl, [method, url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#get, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> getUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#getUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(this, Invocation.method(#getUrl, [url])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(this, Invocation.method(#getUrl, [url])),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> postUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#postUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> putUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#putUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(this, Invocation.method(#putUrl, [url])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(this, Invocation.method(#putUrl, [url])),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> deleteUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patchUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#patchUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#head, [host, port, path]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> headUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#headUrl, [url]),
            returnValue: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientRequest>.value(
              _FakeHttpClientRequest_2(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addCredentials, [url, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addProxyCredentials, [host, port, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HttpClientRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientRequest extends _i1.Mock implements _i3.HttpClientRequest {
  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get followRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#followRedirects),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get maxRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#maxRedirects),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get method =>
      (super.noSuchMethod(
            Invocation.getter(#method),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#method),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#method),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_3(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  int get contentLength =>
      (super.noSuchMethod(
            Invocation.getter(#contentLength),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get bufferOutput =>
      (super.noSuchMethod(
            Invocation.getter(#bufferOutput),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.HttpHeaders get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: _FakeHttpHeaders_4(this, Invocation.getter(#headers)),
            returnValueForMissingStub: _FakeHttpHeaders_4(
              this,
              Invocation.getter(#headers),
            ),
          )
          as _i3.HttpHeaders);

  @override
  List<_i3.Cookie> get cookies =>
      (super.noSuchMethod(
            Invocation.getter(#cookies),
            returnValue: <_i3.Cookie>[],
            returnValueForMissingStub: <_i3.Cookie>[],
          )
          as List<_i3.Cookie>);

  @override
  _i5.Future<_i3.HttpClientResponse> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(this, Invocation.getter(#done)),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(this, Invocation.getter(#done)),
            ),
          )
          as _i5.Future<_i3.HttpClientResponse>);

  @override
  set persistentConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#persistentConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set followRedirects(bool? value) => super.noSuchMethod(
    Invocation.setter(#followRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxRedirects(int? value) => super.noSuchMethod(
    Invocation.setter(#maxRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentLength(int? value) => super.noSuchMethod(
    Invocation.setter(#contentLength, value),
    returnValueForMissingStub: null,
  );

  @override
  set bufferOutput(bool? value) => super.noSuchMethod(
    Invocation.setter(#bufferOutput, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Encoding get encoding =>
      (super.noSuchMethod(
            Invocation.getter(#encoding),
            returnValue: _FakeEncoding_6(this, Invocation.getter(#encoding)),
            returnValueForMissingStub: _FakeEncoding_6(
              this,
              Invocation.getter(#encoding),
            ),
          )
          as _i4.Encoding);

  @override
  set encoding(_i4.Encoding? value) => super.noSuchMethod(
    Invocation.setter(#encoding, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.HttpClientResponse> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(this, Invocation.method(#close, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(this, Invocation.method(#close, [])),
            ),
          )
          as _i5.Future<_i3.HttpClientResponse>);

  @override
  void abort([Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#abort, [exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void add(List<int>? data) => super.noSuchMethod(
    Invocation.method(#add, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void write(Object? object) => super.noSuchMethod(
    Invocation.method(#write, [object]),
    returnValueForMissingStub: null,
  );

  @override
  void writeAll(Iterable<dynamic>? objects, [String? separator = '']) =>
      super.noSuchMethod(
        Invocation.method(#writeAll, [objects, separator]),
        returnValueForMissingStub: null,
      );

  @override
  void writeln([Object? object = '']) => super.noSuchMethod(
    Invocation.method(#writeln, [object]),
    returnValueForMissingStub: null,
  );

  @override
  void writeCharCode(int? charCode) => super.noSuchMethod(
    Invocation.method(#writeCharCode, [charCode]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<dynamic> addStream(_i5.Stream<List<int>>? stream) =>
      (super.noSuchMethod(
            Invocation.method(#addStream, [stream]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}

/// A class which mocks [HttpClientResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientResponse extends _i1.Mock
    implements _i3.HttpClientResponse {
  @override
  int get statusCode =>
      (super.noSuchMethod(
            Invocation.getter(#statusCode),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get reasonPhrase =>
      (super.noSuchMethod(
            Invocation.getter(#reasonPhrase),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#reasonPhrase),
            ),
            returnValueForMissingStub: _i10.dummyValue<String>(
              this,
              Invocation.getter(#reasonPhrase),
            ),
          )
          as String);

  @override
  int get contentLength =>
      (super.noSuchMethod(
            Invocation.getter(#contentLength),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.HttpClientResponseCompressionState get compressionState =>
      (super.noSuchMethod(
            Invocation.getter(#compressionState),
            returnValue: _i3.HttpClientResponseCompressionState.notCompressed,
            returnValueForMissingStub:
                _i3.HttpClientResponseCompressionState.notCompressed,
          )
          as _i3.HttpClientResponseCompressionState);

  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRedirect =>
      (super.noSuchMethod(
            Invocation.getter(#isRedirect),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.RedirectInfo> get redirects =>
      (super.noSuchMethod(
            Invocation.getter(#redirects),
            returnValue: <_i3.RedirectInfo>[],
            returnValueForMissingStub: <_i3.RedirectInfo>[],
          )
          as List<_i3.RedirectInfo>);

  @override
  _i3.HttpHeaders get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: _FakeHttpHeaders_4(this, Invocation.getter(#headers)),
            returnValueForMissingStub: _FakeHttpHeaders_4(
              this,
              Invocation.getter(#headers),
            ),
          )
          as _i3.HttpHeaders);

  @override
  List<_i3.Cookie> get cookies =>
      (super.noSuchMethod(
            Invocation.getter(#cookies),
            returnValue: <_i3.Cookie>[],
            returnValueForMissingStub: <_i3.Cookie>[],
          )
          as List<_i3.Cookie>);

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(
            Invocation.getter(#isBroadcast),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<int>> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<int>> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<int>> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<_i3.HttpClientResponse> redirect([
    String? method,
    Uri? url,
    bool? followLoops,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#redirect, [method, url, followLoops]),
            returnValue: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(
                this,
                Invocation.method(#redirect, [method, url, followLoops]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.HttpClientResponse>.value(
              _FakeHttpClientResponse_5(
                this,
                Invocation.method(#redirect, [method, url, followLoops]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpClientResponse>);

  @override
  _i5.Future<_i3.Socket> detachSocket() =>
      (super.noSuchMethod(
            Invocation.method(#detachSocket, []),
            returnValue: _i5.Future<_i3.Socket>.value(
              _FakeSocket_7(this, Invocation.method(#detachSocket, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Socket>.value(
              _FakeSocket_7(this, Invocation.method(#detachSocket, [])),
            ),
          )
          as _i5.Future<_i3.Socket>);

  @override
  _i5.Stream<List<int>> asBroadcastStream({
    void Function(_i5.StreamSubscription<List<int>>)? onListen,
    void Function(_i5.StreamSubscription<List<int>>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asBroadcastStream, [], {
              #onListen: onListen,
              #onCancel: onCancel,
            }),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.StreamSubscription<List<int>> listen(
    void Function(List<int>)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_8<List<int>>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
            returnValueForMissingStub: _FakeStreamSubscription_8<List<int>>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i5.StreamSubscription<List<int>>);

  @override
  _i5.Stream<List<int>> where(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<S> map<S>(S Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#map, [convert]),
            returnValue: _i5.Stream<S>.empty(),
            returnValueForMissingStub: _i5.Stream<S>.empty(),
          )
          as _i5.Stream<S>);

  @override
  _i5.Stream<E> asyncMap<E>(_i5.FutureOr<E> Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [convert]),
            returnValue: _i5.Stream<E>.empty(),
            returnValueForMissingStub: _i5.Stream<E>.empty(),
          )
          as _i5.Stream<E>);

  @override
  _i5.Stream<E> asyncExpand<E>(_i5.Stream<E>? Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncExpand, [convert]),
            returnValue: _i5.Stream<E>.empty(),
            returnValueForMissingStub: _i5.Stream<E>.empty(),
          )
          as _i5.Stream<E>);

  @override
  _i5.Stream<List<int>> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [onError], {#test: test}),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<S> expand<S>(Iterable<S> Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [convert]),
            returnValue: _i5.Stream<S>.empty(),
            returnValueForMissingStub: _i5.Stream<S>.empty(),
          )
          as _i5.Stream<S>);

  @override
  _i5.Future<dynamic> pipe(_i5.StreamConsumer<List<int>>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(#pipe, [streamConsumer]),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Stream<S> transform<S>(
    _i5.StreamTransformer<List<int>, S>? streamTransformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [streamTransformer]),
            returnValue: _i5.Stream<S>.empty(),
            returnValueForMissingStub: _i5.Stream<S>.empty(),
          )
          as _i5.Stream<S>);

  @override
  _i5.Future<List<int>> reduce(
    List<int> Function(List<int>, List<int>)? combine,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<S> fold<S>(S? initialValue, S Function(S, List<int>)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i5.Future<S>.value(v),
                ) ??
                _FakeFuture_9<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i5.Future<S>.value(v),
                ) ??
                _FakeFuture_9<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
          )
          as _i5.Future<S>);

  @override
  _i5.Future<String> join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [needle]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> forEach(void Function(List<int>)? action) =>
      (super.noSuchMethod(
            Invocation.method(#forEach, [action]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> every(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#every, [test]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> any(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#any, [test]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<R> cast<R>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _i5.Stream<R>.empty(),
            returnValueForMissingStub: _i5.Stream<R>.empty(),
          )
          as _i5.Stream<R>);

  @override
  _i5.Future<List<List<int>>> toList() =>
      (super.noSuchMethod(
            Invocation.method(#toList, []),
            returnValue: _i5.Future<List<List<int>>>.value(<List<int>>[]),
            returnValueForMissingStub: _i5.Future<List<List<int>>>.value(
              <List<int>>[],
            ),
          )
          as _i5.Future<List<List<int>>>);

  @override
  _i5.Future<Set<List<int>>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: _i5.Future<Set<List<int>>>.value(<List<int>>{}),
            returnValueForMissingStub: _i5.Future<Set<List<int>>>.value(
              <List<int>>{},
            ),
          )
          as _i5.Future<Set<List<int>>>);

  @override
  _i5.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#drain, [futureValue]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i5.Future<E>.value(v),
                ) ??
                _FakeFuture_9<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
            returnValueForMissingStub:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i5.Future<E>.value(v),
                ) ??
                _FakeFuture_9<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
          )
          as _i5.Future<E>);

  @override
  _i5.Stream<List<int>> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<List<int>> takeWhile(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<List<int>> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<List<int>> skipWhile(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Stream<List<int>> distinct([
    bool Function(List<int>, List<int>)? equals,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#distinct, [equals]),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);

  @override
  _i5.Future<List<int>> firstWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<int>> lastWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<int>> singleWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<List<int>> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Stream<List<int>> timeout(
    Duration? timeLimit, {
    void Function(_i5.EventSink<List<int>>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i5.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<int>>.empty(),
          )
          as _i5.Stream<List<int>>);
}

/// A class which mocks [HttpHeaders].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpHeaders extends _i1.Mock implements _i3.HttpHeaders {
  @override
  int get contentLength =>
      (super.noSuchMethod(
            Invocation.getter(#contentLength),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get chunkedTransferEncoding =>
      (super.noSuchMethod(
            Invocation.getter(#chunkedTransferEncoding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set date(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#date, value),
    returnValueForMissingStub: null,
  );

  @override
  set expires(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#expires, value),
    returnValueForMissingStub: null,
  );

  @override
  set ifModifiedSince(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#ifModifiedSince, value),
    returnValueForMissingStub: null,
  );

  @override
  set host(String? value) => super.noSuchMethod(
    Invocation.setter(#host, value),
    returnValueForMissingStub: null,
  );

  @override
  set port(int? value) => super.noSuchMethod(
    Invocation.setter(#port, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentType(_i3.ContentType? value) => super.noSuchMethod(
    Invocation.setter(#contentType, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentLength(int? value) => super.noSuchMethod(
    Invocation.setter(#contentLength, value),
    returnValueForMissingStub: null,
  );

  @override
  set persistentConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#persistentConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set chunkedTransferEncoding(bool? value) => super.noSuchMethod(
    Invocation.setter(#chunkedTransferEncoding, value),
    returnValueForMissingStub: null,
  );

  @override
  List<String>? operator [](String? name) =>
      (super.noSuchMethod(
            Invocation.method(#[], [name]),
            returnValueForMissingStub: null,
          )
          as List<String>?);

  @override
  String? value(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#value, [name]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void add(String? name, Object? value, {bool? preserveHeaderCase = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #add,
          [name, value],
          {#preserveHeaderCase: preserveHeaderCase},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void set(String? name, Object? value, {bool? preserveHeaderCase = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #set,
          [name, value],
          {#preserveHeaderCase: preserveHeaderCase},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void remove(String? name, Object? value) => super.noSuchMethod(
    Invocation.method(#remove, [name, value]),
    returnValueForMissingStub: null,
  );

  @override
  void removeAll(String? name) => super.noSuchMethod(
    Invocation.method(#removeAll, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void forEach(void Function(String, List<String>)? action) =>
      super.noSuchMethod(
        Invocation.method(#forEach, [action]),
        returnValueForMissingStub: null,
      );

  @override
  void noFolding(String? name) => super.noSuchMethod(
    Invocation.method(#noFolding, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}
