// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmGo1YIY2B1G08tup7q41mOnpgHXY5BU',
    appId: '1:430718961228:web:ce69e50259a70557c6d6e9',
    messagingSenderId: '430718961228',
    projectId: 'homesolreports',
    authDomain: 'homesolreports.firebaseapp.com',
    storageBucket: 'homesolreports.firebasestorage.app',
    measurementId: 'G-VY0SEPYHB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl9PGXRCtOe9CBFTR9kue9JLyV7OGlcbg',
    appId: '1:430718961228:android:f6b1ef7c9bee8b0cc6d6e9',
    messagingSenderId: '430718961228',
    projectId: 'homesolreports',
    storageBucket: 'homesolreports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5V47s_pvDbibSy9kQcAVvS1BgrVimZCQ',
    appId: '1:430718961228:ios:b6946edc5c398c48c6d6e9',
    messagingSenderId: '430718961228',
    projectId: 'homesolreports',
    storageBucket: 'homesolreports.firebasestorage.app',
    iosBundleId: 'com.example.syndicate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5V47s_pvDbibSy9kQcAVvS1BgrVimZCQ',
    appId: '1:430718961228:ios:f1ebac33c340febcc6d6e9',
    messagingSenderId: '430718961228',
    projectId: 'homesolreports',
    storageBucket: 'homesolreports.firebasestorage.app',
    iosBundleId: 'com.example.homesol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbmGo1YIY2B1G08tup7q41mOnpgHXY5BU',
    appId: '1:430718961228:web:989de1bbd35e1d64c6d6e9',
    messagingSenderId: '430718961228',
    projectId: 'homesolreports',
    authDomain: 'homesolreports.firebaseapp.com',
    storageBucket: 'homesolreports.firebasestorage.app',
    measurementId: 'G-MCBG07LSN7',
  );
}
